- name: Install nginx
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: Copy roboshop config file
  ansible.builtin.template:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf

- name: Copy nginx config file
  ansible.builtin.template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: Clean the old app content
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: Create the app directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

- name: Download the app content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name: Start Nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: true

- name: Install filebeat
  ansible.builtin.import_role:
    name: elk
    tasks_from: filebeat

- name: import the node exporter
  ansible.builtin.import_role:
    name: prometheus
    tasks_from: node_exporter



