- name: copy the prometheus configuration
  ansible.builtin.template:
    src: "{{ item }}.yml"
    dest: /opt/prometheus/{{ item }}.yml
  loop:
    - prometheus
    - alerts

- name: restart prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: restarted

- name: check if the prometheus service is running or not
  ansible.builtin.wait_for:
    port: 9090
    delay: 10
    timeout: 15

