- name: copy the prometheus configuration
  ansible.builtin.template:
    src: prometheus.yml
    dest: /opt/prometheus/prometheus.yml

- name: copy the alerts configuration
  ansible.builtin.template:
    src: alerts.yml
    dest: /opt/prometheus/alerts.yml

- name: restart prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: restarted

- name: check if the prometheus service is running or not
  ansible.builtin.wait_for:
    port: 9090
    delay: 10
    timeout: 15

